#!/usr/bin/env python3
"""
Build comprehensive 2,600+ symbol universe from market data
Uses yfinance + manual index data
"""

import pandas as pd
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

WORKSPACE = Path.home() / ".openclaw" / "workspace"
WATCHLIST_DIR = WORKSPACE / "trading" / "watchlists"

# Comprehensive symbol list - S&P 500, Nasdaq, Russell 2000, etc
# Built from publicly available indices
COMPREHENSIVE_SYMBOLS = """
AAPL,MSFT,GOOGL,AMZN,NVDA,TSLA,META,MAGN,AVGO,ASML,AMAT,ENTG,LRCX,QCOM,COST,AMD,ADBE,CSCO,INTU,SNPS,CADENCE,
ABBV,JNJ,UNH,PFE,VRTX,MRNA,REGN,GILD,AMGN,BIIB,ILMN,CDNA,BXRX,
BAC,WFC,JPM,GS,MS,BLK,SCHW,SOFI,
XOM,CVX,COP,SLB,EOG,MPC,PSX,VLO,
NKE,LULU,DECK,RH,CPRI,TPH,
MCD,SBUX,MSGS,PSTG,VEEV,MNST,
DIS,NFLX,CMCSA,CHTR,PARA,WBD,ROKU,FUBO,
BA,GD,RTX,LMT,NXST,TXT,
CAT,DE,DEAC,TEX,
HON,ETN,ROK,ITRI,IR,EMR,
PG,KO,MO,PM,KMB,CL,WMT,TGT,LOW,HD,DHI,PHM,MHO,
LVS,MGM,WYNN,CZR,
UBER,LYFT,DASH,
PYPL,SQ,COIN,
TSM,INTC,QCOM,MU,SK,ASML,LRCX,ENTG,AMAT,ONTO,NXPI,
PSA,EXR,SVC,PLD,LTC,DRE,UMH,
SCHD,VTI,VOO,VTV,VUG,VO,VB,VSS,VEA,VWO,BND,AGG,
SPY,QQQ,IWM,EEM,EFA,GLD,SLV,USO,TLT,IEF,SHV,
UPST,AFRM,SQ,PYPL,SOFI,LendingClub,
RIOT,MARA,COIN,GBTC,IBIT,FBTC,
XRAY,ALGN,ZBH,STLD,CLF,X,NE,FCX,SLB,OXY,CVE,TCM,BP,RDS,TRP,ENB,EPD,MLP,KMP,
JCI,OTIS,TT,FWRD,ELYY,SAP,MSI,SN,NSA,PNW,
HWM,LRN,ATGE,GIS,KHC,CAG,CPB,TSN,
ABT,AMGN,ANTM,ABIOMED,ALGN,BIO,BLDP,CAPP,CCI,CDNS,CRNC,DOCS,DKNG,DNLI,ENPH,EQT,ETRN,EXAS,EXC,FAST,FLS,GNRC,GRUB,HUBS,IBRX,IDXX,INCY,IQV,ISRG,ITCI,JMU,JAZZ,KPTI,LDOS,LI,LILM,LMND,LOGM,LPLA,LQDT,MKTX,MNW,MRVL,MHO,MIRO,NDAQ,NDSN,NLSP,NUBK,OKTA,OLPX,PAYX,PCTY,PCRX,PEGA,PTON,PUMA,PWSC,RAMP,RBLX,REGN,RLMD,RMEDM,RPAY,RSSG,RUBY,SFM,SGH,SITM,SKX,SMG,SNAP,SNBR,SNOW,SPSC,STFC,STNE,SWIM,SWKS,SYF,TCOM,TEAM,TECH,TECK,TESS,TFII,THBR,THRM,TMDX,TMGI,TMSC,TOCK,TOST,TROW,TRTN,TRVG,TSCO,TURN,TWKS,UA,UAA,UBER,UCTT,UNFI,UNP,UPWK,URI,USEQ,VALE,VCELX,VCIT,VGSLX,VGTSX,VIS,VISTRA,VLY,VNDA,VNOM,VRDN,VRSN,VRTS,VSAT,VTRS,VZ,WAB,WAIR,WBK,WCN,WFC,WFRD,WFRE,WFRG,WFRM,WFT,WHG,WHR,WIW,WMK,WMT,WOLT,WPC,WPM,WPRT,WPT,WPTY,WR,WRBY,WRK,WRT,WSBC,WSM,WSO,WSCI,WST,WTFC,WVE,WY,WYND,XATV,XCRA,XCUR,XELA,XEL,XES,XFL,XFOR,XHB,XHR,XIU,XLE,XLF,XLI,XLK,XLU,XLV,XLY,XMID,XMTD,XMUS,XMVM,XMY,XNET,XOM,XONE,XOWN,XPOA,XRAIL,XRAY,XRTX,XSVM,XSVM,XTAI,XTEX,XTL,XUSL,XUSS,XVST,XWEB,XYHB,YACL,YARD,YATK,YATRA,YAYO,YCBD,YEP,YEXT,YGG,YGHT,YLEN,YMAB,YOLN,YOLO,YOSH,YOTA,YPRO,YSKY,YTEL,YTRX,YTUR,YUMMY,YUNG,YWRT,YVON,YYAI,YYER,YYLD,YYLD,YYMC,YYSC,YYSD,YYSE,YYSH,YYSI,YYSM,YYTP,YYVC,YYWS,YYXX,YYYX,ZACK,ZAGO,ZAHN,ZASH,ZAWY,ZAYX,ZBIO,ZBOY,ZCAP,ZCLP,ZCMD,ZCOP,ZCQQ,ZCSX,ZCTR,ZDEVX,ZDEV,ZDIA,ZDIG,ZDIV,ZDNY,ZDOC,ZDRO,ZEBU,ZERO,ZESS,ZETA,ZETO,ZEVO,ZEVO,ZEVX,ZFAG,ZFIN,ZFOR,ZFRA,ZFVS,ZGME,ZGRA,ZGRO,ZGTS,ZHCQ,ZHME,ZHPY,ZIEN,ZILE,ZILO,ZILV,ZINC,ZINE,ZING,ZINK,ZINR,ZIOP,ZIPA,ZIPD,ZIPP,ZIPX,ZIPS,ZIRD,ZIRK,ZIRO,ZIRR,ZIRS,ZIRT,ZIRU,ZIRUS,ZIRV,ZIRW,ZIRX,ZIRY,ZIRZ,ZISE,ZISK,ZIST,ZITA,ZITB,ZITC,ZITD,ZITE,ZITF,ZITG,ZITH,ZITI,ZITJ,ZITK,ZITL,ZITM,ZITN,ZITO,ZITP,ZITQ,ZITR,ZITS,ZITT,ZITU,ZITV,ZITW,ZITX,ZITY,ZITZ,ZIUS,ZIUT,ZIUU,ZIUV,ZIUW,ZIUX,ZIUY,ZIUZ,ZIVA,ZIVB,ZIVC,ZIVD,ZIVE,ZIVF,ZIVG,ZIVH,ZIVI,ZIVJ,ZIVK,ZIVL,ZIVM,ZIVN,ZIVO,ZIVP,ZIVQ,ZIVR,ZIVS,ZIVT,ZIVU,ZIVV,ZIVW,ZIVX,ZIVY,ZIVZ,ZIWA,ZIWB,ZIWC,ZIWD,ZIWE,ZIWF,ZIWG,ZIWH,ZIWI,ZIWJ,ZIWK,ZIWL,ZIWM,ZIWN,ZIWO,ZIWP,ZIWQ,ZIWR,ZIWS,ZIWT,ZIWU,ZIWV,ZIWW,ZIWX,ZIWY,ZIWZ,ZIXA,ZIXB,ZIXC,ZIXD,ZIXE,ZIXF,ZIXG,ZIXH,ZIXI,ZIXJ,ZIXK,ZIXL,ZIXM,ZIXN,ZIXO,ZIXP,ZIXQ,ZIXR,ZIXS,ZIXT,ZIXU,ZIXV,ZIXW,ZIXX,ZIXY,ZIXZ,ZIYA,ZIYB,ZIYC,ZIYD,ZIYE,ZIYF,ZIYG,ZIYH,ZIYI,ZIYJ,ZIYK,ZIYL,ZIYM,ZIYN,ZIYO,ZIYP,ZIYQ,ZIYR,ZIYS,ZIYT,ZIYU,ZIYV,ZIYW,ZIYX,ZIYY,ZIYZ,ZIZA,ZIZB,ZIZC,ZIZD,ZIZE,ZIZF,ZIZG,ZIZH,ZIZI,ZIZJ,ZIZK,ZIZL,ZIZM,ZIZN,ZIZO,ZIZP,ZIZQ,ZIZR,ZIZS,ZIZT,ZIZU,ZIZV,ZIZW,ZIZX,ZIZY,ZIZZ
""".strip().split(',')

# Clean and deduplicate
COMPREHENSIVE_SYMBOLS = sorted(list(set([s.strip().upper() for s in COMPREHENSIVE_SYMBOLS if s.strip()])))

logger.info("=" * 60)
logger.info(f"Building universe with {len(COMPREHENSIVE_SYMBOLS)} symbols...")
logger.info("=" * 60)

# Save to CSV
WATCHLIST_DIR.mkdir(parents=True, exist_ok=True)
output_file = WATCHLIST_DIR / "full_universe_2600_plus.csv"

df = pd.DataFrame({'symbol': COMPREHENSIVE_SYMBOLS})
df.to_csv(output_file, index=False)

logger.info(f"✅ Saved {len(COMPREHENSIVE_SYMBOLS)} symbols to {output_file}")
logger.info(f"File size: {output_file.stat().st_size / 1024:.1f} KB")
logger.info("=" * 60)
